// Generated by typings
// Source: custom-typings/node-polyglot.d.ts
declare module 'node-polyglot' {
interface Translations {
  [language: string]: {[word: string]: any}
}

class Polyglot {
  extend(translations: Translations): void;
  t(key: string, options: any); void;
}

export = Polyglot;
}
