// Generated by typings
// Source: custom-typings/switch-path.d.ts
declare module 'switch-path' {
export interface RouteDefinitions {
  [pathname: string]: any;
}

export default function switchPath(path: string, routes: RouteDefinitions): { path: string, value: any };
}
